- README.md
Fix license badge link after #252 changed the license filename.
Fixes BBS-301.
) (if it is not the case, please create an issue
first).
> [BBS-301] Fix license badge link

- README.md
- docker/base.Dockerfile
- setup.py
https://github.com/BlueBrain/Search/pull/242 forgot to change things related to Python 3.6:
Fixes [BBS-299](https://bbpteam.epfl.ch/project/issues/browse/BBS-299).
https://github.com/BlueBrain/Search/blob/fb1e7885961f70c8f4d9174d7200b758ffda1b67/setup.py#L88
This causes the installation of BBS to fails on Python 3.6 without a clear idea of the reason.
`NumPy` 1.20.1 requires Python >= 3.7. No artefacts are published on PyPI for Python 3.6. When installing BBS on Python 3.6, the following strange error is thrown:
```
ERROR: Could not find a version that satisfies the requirement numpy==1.20.1
ERROR: No matching distribution found for numpy==1.20.1
```
Installation of `python3.6-dev`.
Mention of `Python 3.6`.
Mention of Docker image `python:3.6`.
Mention of `Python 3.6`.
Mention of Tox …
> [BBS-299] Fix leftovers from dropping Python 3.6

- notebooks/STS_evaluation.ipynb
https://github.com/BlueBrain/Search/pull/247 removed the model `Sent2Vec`.
This model was used in the notebook `STS_evaluation.ipynb`.
The PR replaces this by making use of the setup done in the `Getting Started` from the README.
Fixes [BBS-303](https://bbpteam.epfl.ch/project/issues/browse/BBS-303).
Follow the instructions from the [Getting Started](https://github.com/BlueBrain/Search/tree/b230221c6a086036f3709ea8232c8d4a4597d969#getting-started) but:
1. only until the end of the section [Compute the sentence embeddings](https://github.com/BlueBrain/Search/tree/b230221c6a086036f3709ea8232c8d4a4597d969#compute-the-sentence-embeddings),
2. and with the modifications below,
In [Prerequisites](https://github.com/BlueBrain/Search/tree/b230221c6a086036f3709ea8232c8d4a4597d969#prerequisites): …
> [BBS-303] Link STS_evaluation.ipynb and the Getting Started

- README.md
- docs/source/whatsnew.rst
Fixes [BBS-240](https://bbpteam.epfl.ch/project/issues/browse/BBS-240).
This PR adds the DOI badge to the [Zenodo record](https://zenodo.org/record/4563999) of Blue Brain Search.
Each time a release is published on GitHub, an archive of the release will be uploaded on Zenodo.
Such archive will get a unique DOI. So, each release is uniquely citable.
A DOI is also assigned to the Zenodo record. This DOI points to the latest released version.
This is the DOI from the badge.
> [BBS-240] Make Blue Brain Search citable

- README.md
- docker/mining.sh
- docs/source/whatsnew.rst
Fixes [BBS-266](https://bbpteam.epfl.ch/project/issues/browse/BBS-266).
~Currently blocked by [BBS-306](https://bbpteam.epfl.ch/project/issues/browse/BBS-306).~
Otherwise, after the tests are successful:
Adapt the Getting Started from the `README` to use the DVC remote from Zenodo.
Follow the Getting Stared from the `README` after
```
git clone --depth 1 --branch bbs_266 https://github.com/BlueBrain/Search.git
```
The notebook at the end should be usable for search and mining.
```
wget <fixme>
tar xf bbs_dvc_remote.tar.gz
git clone --depth 1 --branch v0.1.0 https://github.com/BlueBrain/Search.git
cd Search/
cp /path/to/prodigy/wheel .
dvc remote add --default local ../bbs_dvc_remote
```
```
dvc pull
```
should retrieve all DVC tracked data and models successfully.
After
```
docker build …
```
> [BBS-266] Adapt Getting Started for DVC remote from Zenodo

- README.md
Tiny change, just replacing GitHub Releases badge with PyPI one.
**Rationale**: We are now publishing our package with PyPI, so there does not seem to be reasons to use GitHub Releases any more.
> Use PyPI badge for latest release

- README.md
Just add a badge for supported Python versions.
This helps people to figure out compatibility with their Python environment.
Render the changed README. The badge should display Python 3.7 to 3.9.
> [SUGGESTION] Add a badge for supported Python versions

- data_and_models/pipelines/ner/add_er.py
It seems like `spacy` does not guarantee that labels (entity types) of the `EntityRuler` are sorted deterministically. This becomes a problem when we are saving the model because each time the `meta.json` might have a different MD5 hash.
`spacy` uses the `set` datastructure to create all the labels ([actual code](https://github.com/explosion/spaCy/blob/97bcf2ae3a03cf97fd473062c1793e3d18ef2820/spacy/pipeline/entityruler.py#L180))
```python
@property
def labels(self) -> Tuple[str, ...]:
"""All labels present in the match patterns.
RETURNS (set): The string labels.
DOCS: https://spacy.io/api/entityruler#labels
"""
keys = set(self.token_patterns.keys())
keys.update(self.phrase_patterns.keys())
all_labels = set()
for l in keys:
if self.ent_id_sep in l:
label, _ = self._split_label(l) …
```
> [BBS 307] EntityRuler labels nondeterministic sorting

- data_and_models/pipelines/sentence_embedding/eval.py
- docker/embedding.Dockerfile
- docker/mining.Dockerfile
- docker/mining_cache.Dockerfile
- docker/search.Dockerfile
- docker/utils.sh
- docs/source/whatsnew.rst
- requirements.txt
- setup.py
- tox.ini
Fixes #292 
Remove all NLTK dependencies since we don't use it any more.
I did the following grep on our code base:
```bash
find . -type f ! -path './.*' ! -path './venv/*' | xargs grep -in nltk
```
Any other places NLTK could be?
(if needed)
(if needed)
(if needed)
> Remove NLTK Dependencies

- src/bluesearch/database/mining_cache.py
Fixes #300 .
With the latest SQLAlchemy version `1.4.0` the following call leads to an exception:
```python
engine.dialect.has_table(engine, table_name)
```
It can be fixed by replacing it with
```python
engine.has_table(table_name)
```
```bash
pip install sqlalchemy==1.4.0
pytest tests/test_database/test_mining_cache.py::TestCreateMiningCache
```
(if needed)
(if needed)
(if needed)
> Fix the has_table call

- data_and_models/pipelines/sentence_embedding/params.yaml
- docs/source/whatsnew.rst
- src/bluesearch/embedding_models.py
- src/bluesearch/entrypoint/embedding_server.py
- src/bluesearch/server/embedding_server.py
- src/bluesearch/server/search_server.py
- tests/test_embedding_models.py
- tests/test_entrypoint/test_embedding_server.py
- tests/test_server/test_search_server.py
Fixes #275 .
Previously we were using a dedicated class for SBioBERT, where in particular we defined a method for the mean pooling with attention mask prescribed [here](https://huggingface.co/sentence-transformers/bert-base-nli-mean-tokens).
This PR reduces the complexity of that solution by leveraging [`UKPLab/sentence-transformers`](https://github.com/UKPLab/sentence-transformers/) and the pretrained model [`gsarti/biobert-nli`](https://huggingface.co/gsarti/biobert-nli) through the interface provided by our `bluesearch.embedding_models.SentTransformers`.
The embeddings produced using `SBioBERT` did not change. You can try to run
```python
from bluesearch.embedding_models import get_embedding_model
sbiobert = get_embedding_model("SBioBERT")
sentences = [  # put whatever you want here …
```
> Remove SBioBERT dedicated class

- setup.py
Instead of requiring
- `SQLAlchemy`
- `mysqlclient`
- `pymysql`
in `setup.py` require
- `SQLAlchemy[mysql,pymysql]`
which does exactly the same thing.
> Simplify SQLAlchemy Requirements

- README.md
- docker/mining.Dockerfile
- docker/mining.sh
- docker/mining_cache.Dockerfile
- docker/mining_cache.sh
- docker/utils.sh
JIRA: [BBS-255](https://bbpteam.epfl.ch/project/issues/browse/BBS-255)
Potentially related: [BBS-306](https://bbpteam.epfl.ch/project/issues/browse/BBS-306)
The main change is to replace the calls
```bash
ssh_check
dvc_pull_models
```
in `docker/mining.sh` and `docker/mining_cache.sh` by
```bash
dvc_configure_ssh_remote_authentication "$BBS_SSH_USERNAME"
dvc_pull_models "$DATA_DIR"
```
This eliminates hard-coded paths in thses functions and allows to re-use them elsewhere with different parameters.
In our `README.md` file we do the steps covered by `dvc_configure_ssh_remote_authentication` and `dvc_pull_models` manually. There's also a passage saying that "NB: At the moment, `dvc_pull_models` from `Search/docker/utils.sh` is not yet usable as it works only when inside the `bbs_` Docker …
> [BBS-255] Generalize DVC initialization to not only src/ context

- data_and_models/pipelines/ner/Dockerfile
- data_and_models/pipelines/ner/dvc.lock
- data_and_models/pipelines/sentence_embedding/Dockerfile
- data_and_models/pipelines/sentence_embedding/dvc.lock
- docs/source/whatsnew.rst
- requirements.txt
- setup.py
Fixes #273.
Upgrades to `dvc==2.0.6` and releases `bluesearch v0.1.1`.
1. I used to consistently get the error 
```ValueError: unsupported pickle protocol: 5```
when trying to `dvc pull` or `dvc add` using `dvc>=2` in a directory where I still had the old cache generated using `dvc<2`. But for some reason I cannot reproduce the error any more! 🤷  Anyway, should you see that error, try to `rm -rf .dvc/cache` and then re-populate your cache with a `dvc pull` (or `dvc fetch`)—this worked for me.
2. The new `dvc.lock` format is only slightly different but breaks backward compatibility. Also, `git diff` is confused by the new format, so please see "How to test" below to see how to visualize the changes.
3. Here are some highlights of the new elemnents introduced in `dvc 2.0`.
1. [**ML …
> Upgrade to dvc>=2  + release bluesearch v0.1.1

- docs/source/whatsnew.rst
- src/bluesearch/embedding_models.py
- src/bluesearch/mining/eval.py
- tests/conftest.py
- tests/test_mining/test_eval.py
Fixes #336.
This PR fixes bugs in our NER evaluation functions of `bluesearch.mining.eval`.
These discrepancies were first identified [here](https://github.com/BlueBrain/Search/issues/336#issuecomment-826830138) and [here](https://github.com/BlueBrain/Search/issues/336#issuecomment-823244116).
Unit tests were added to introduce cases that used to fail and are now passing.
(if needed)
(if needed)
> Fix bugs in NER evaluation

- src/bluesearch/mining/eval.py
Fixes #361.
The isssue was due to the fact that the returned values of `ner_report` were the result of a reduce operation (`.sum()` in this case) on a `pd.Series` of integers. And integers are represented by `np.int64` in `pandas`, rather than the native `int` type of Python.
Two possible solutions (see also [here](https://stackoverflow.com/questions/9452775/converting-numpy-dtypes-to-native-python-types)).
1. Manually cast to desired type, e.g. `int(series.sum())`
2. Extract the underlying value as a Python scalar with [`.item()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.item.html), e.g. `series.sum().item()`
I think option 2 is better, since it's more generic: `np.float32` will be automatically converted to `float`, `np.int64` to `int` etc. So I used this approach.
The …
> Fix NER eval bug — dtype conversion from NumPy's to Python's

- data_and_models/pipelines/ner/config.cfg
Fixes #356.
Training the Transformer-based NER models (see #351) takes too long on CPU (almost a full day).
The training is happening on CPU because of reproducibility issues (see #343).
The goal was to find `when to stop training to reduce its duration` while keeping the accuracy (see issue description).
An experiment was conducted. Its results are summarized in https://github.com/BlueBrain/Search/issues/356#issuecomment-842451358, https://github.com/BlueBrain/Search/issues/356#issuecomment-842452733, and https://github.com/BlueBrain/Search/issues/356#issuecomment-844254751.
This PR adjusts the NER training duration parameters accordingly to the outcome of the experiment.
⚠️ The issue addressed by this PR (#356) is in the same sprint has the issue introducing the point (#351) it fixes. …
> Reduce the training time on CPU of Transformer-based NER pipelines

- docs/source/whatsnew.rst
- setup.py
- src/bluesearch/database/mining_cache.py
- src/bluesearch/embedding_models.py
- src/bluesearch/mining/entity.py
- src/bluesearch/mining/eval.py
- src/bluesearch/server/embedding_server.py
- src/bluesearch/server/search_server.py
- src/bluesearch/widgets/article_saver.py
- src/bluesearch/widgets/mining_schema.py
- src/bluesearch/widgets/search_widget.py
- tests/test_database/test_cord_19.py
- tests/test_database/test_mining_cache.py
- tests/test_mining/test_attribute.py
- tests/test_server/test_mining_server.py
- tests/test_sql.py
- tests/test_widgets/test_article_saver.py
- tests/test_widgets/test_mining_schema.py
- tests/test_widgets/test_search_widget.py
- tox.ini
Closes #363 .
- Add `flake8-bugbear`, `flake8-comprehensions`, and `flake8-docstrings` to the linting pipeline
- Add `isort` configuration to `tox.ini` (instead of providing configuration on the command line)
- Upgrade `black` and `isort`
- Upgrade `pandas-stubs`, this makes the artificial casting to `pd.DataFrame` that we introduced obsolete.
- Streamline the command line parameters in the `lint` and `format` tox sections
- Add possibility to provide files for linting and formatting as positional arguments to tox.
The main changes are in `tox.ini`, all other changes are fixes for new linting errors.
The linting should pass:
```bash
$ tox -e lint
```
Furthermore, now it's also possible to lint/format selected paths by providing them as positional arguments to tox:
```bash
$ tox -e format …
```
> Add new linting components

- src/bluesearch/mining/eval.py
In `bluesearch.minig.eval.ner_confusion_matrix` we use `sklearn.metrics.confusion_matrix`
but the corresponding import was missing.
(if needed)
(if needed)
(if needed)
> Add missing sklearn.metrics import in eval module

- setup.py
Fixes #397.
Some of the URLs in the `setup.py` were only accessible from Blue Brain intranet.
They are now pointing to public URLs.
1. Clicking on the links of the URLs should now work w/o need to login in the Blue Brain system.
2. When we push to PyPI, the links should be updated.
> Update URLs in setup.py

- src/bluesearch/database/article.py
- src/bluesearch/database/cord_19.py
- tests/conftest.py
- tests/test_database/test_article.py
Fixes #371 .
I drafted a proposition for the article data abstraction. Roughly the idea is the following:
- The article data is captured by the `Article` class.
- For data injestion the `ArticleParser` should be subclassed for each data source.
- For data export/writing it's possible to implement a dedicated class e.g. an `ArticleJSONWriter`.
You can use the following script:
```python
import json
from bluesearch.database.article import Article, CORD19ArticleParser
json_file_path = "<path to a CORD-19 JSON file>"
with open(json_file_path) as fp:
json_data = json.load(fp)
parser = CORD19ArticleParser(json_data)
article = Article.parse(parser)
print("Article:")
print(article)
print("End.")
```
(if needed)
(if needed)
(if needed)
(if a …
> Define JSON schema of machine-readable parses

- data_and_models/pipelines/sentence_embedding/dvc.lock
- data_and_models/pipelines/sentence_embedding/dvc.yaml
- docs/source/whatsnew.rst
Fixes #396.
See #396 for the motivation behind the PR.
The solution from the PR (bc8f9cc24111841c15c2b1ee5c8daa2af0e86c1a):
1. separates the evaluation of the models we didn't train (new stage `evaluation_external`)
2. adds the model data as `deps` for each models we trained
Note:
The `cmd` field has been reformatted for better readability.
The dvc.lock has been updated (80b308c7d268f2411403a868865e2a7420aeb07b) and `dvc push` has been executed.
The following now works without error:
```
git clone --branch issue_396 https://github.com/BlueBrain/Search/
export PIPELINE=data_and_models/pipelines/sentence_embedding/dvc.yaml
dvc pull -d $PIPELINE
dvc repro -f $PIPELINE
```
> Fix the definition of DVC pipeline sentence_embedding

- data_and_models/pipelines/ner/config.cfg
- data_and_models/pipelines/ner/dvc.lock
- docs/source/whatsnew.rst
Fixes #385.
During the creation of the mining_cache, an issue was raised (check the issue #385). Several possibilities to handle this issue were considered (on spaCy and transformers side).
Proposed solution: Modify initial `config.cfg` before training the NER models.
If everyone agrees with this way of handling the issue, 
(if needed)
(if needed)
(if needed)
> #385 Huggingface tokenizer provides incorrect model_max_length

- src/bluesearch/entrypoint/database/add.py
- src/bluesearch/entrypoint/database/parse.py
- tests/entrypoint/database/test_add.py
- tests/entrypoint/database/test_parse.py
Fixes #436 .
After profiling `bbs_database parse` and `add`, it became clear that running these commands once per each file is not the most efficient approach (see detailed results [here](https://github.com/BlueBrain/Search/issues/436#issuecomment-918981263)).
With this PR, the interface of these two commands is modified to support also running on all the files contained in a given directory. Notice that the output parameter has slightly changed as well.
**Before this PR**
```bash
bbs_database parse pmc-xml some_article.xml some_article.pkl
bbs_database add database.db some_article.pkl
```
**After this PR**
```bash
bbs_database parse pmc-xml some_article.xml pkl_files/  # parse single file
bbs_database parse pmc-xml xml_files/ pkl_files/        # parse multiple files
bbs_database add …
```
> `bbs_database parse` and `add`: add support for multiple files

- src/bluesearch/database/article.py
- src/bluesearch/entrypoint/database/add.py
- tests/data/sample_file.xml
- tests/unit/database/test_article.py
- tests/unit/entrypoint/database/test_add.py
Fixes #448.
This PR handles the concrete parsing of articles identifiers (currently namely: `(PubMed ID, PMC ID and DOI)`) and the generation of the unique ID. 
- All of them can be found in the schema of `XML` files of PMC papers. 
- Only `PMC` id is specified concerning the `json` files of CORD-19.
- From PMC papers on DGX1:
- All of them possess a PMC ID.
- PubMed ID is specified in 89.85 %.
- DOI is specified in 83.51 %.
(if needed)
(if needed)
(if needed)
> #448 Create unique article_id column when bbs_database add is called

- docs/source/whatsnew.rst
- requirements.txt
- setup.py
- src/bluesearch/database/article.py
- src/bluesearch/entrypoint/database/add.py
- src/bluesearch/entrypoint/database/parse.py
- tests/unit/database/test_article.py
- tests/unit/entrypoint/database/test_add.py
- tests/unit/entrypoint/database/test_parse.py
Fixes #422.
Between parsing and loading, the data of `Article` instances are serialized as `pickle` files. This implements the best practice named 'separation of concerns'. Indeed, the logic for parsing raw data into `Article` instances and the logic for loading `Article` instances in the database are then separated.
The issue #422 wants to move away from the `pickle` format. Indeed, the tool `bandit` warns against it. If someone would have added malicious code to the serialized `Article` instances, deserializing the data could lead to execute malicious code.
➡️ The goal of the current PR is then to replace the `pickle` format with another format. This other format is `JSON`.
A Python library named `mashumaro` ([PyPI](https://pypi.org/project/mashumaro/)), lets serialize and deserialize a …
> Add JSON serialization for dataclass Article

- docs/source/whatsnew.rst
- src/bluesearch/entrypoint/database/add.py
- tests/unit/entrypoint/database/test_add.py
Fixes #461.
Two new behaviours for `bbs_database`:
1. If no article was loaded from the given path, stop and don't load the NLP model to get sentences (fail faster)
2. If no sentence was extracted from the given path, stop.
The following automatic tests in `test_add.py` check the new behaviours:
- `test_no_articles()`
- `test_no_sentences()`
> Stop when no article or sentence to load in the database

- src/bluesearch/entrypoint/database/add.py
- src/bluesearch/entrypoint/database/convert_pdf.py
- src/bluesearch/entrypoint/database/init.py
- src/bluesearch/entrypoint/database/parent.py
- src/bluesearch/entrypoint/database/parse.py
- tests/integration/test_bbs_database.py
- tests/unit/entrypoint/database/test_parent.py
- tests/unit/entrypoint/test_entrypoint_installation.py
Closes #486, closes #488, closes #487, closes #421
* Introduced `-v` and `-vv` flag in all subcommands (using a parent parser) that controls the logging level
* Using `init_parser` everywhere which is a function that modifies the parser in place
* Make CLI creation "semi-dynamic" (inspired by discussion with @Stannislav)
Each of the `add`, `init`, `parse`, `convert-pdf` supports an optional flag `-v` or `-vv` controlling the verbosity.
Internally, this is the mapping between the logging level and the CLI flag:
```
nothing -> logging.WARNING
-v      -> logging.INFO
-vv     -> logging.DEBUG
```
For example
```
bbs_database init -v temp_db.sqlite
```
* Feel free to propose a different formatting of the LogRecords
* Currently, we only have a standard output handler, however, we can add more …
> New CLI organization + introducing logging

- tests/unit/entrypoint/database/test_add.py
- tests/unit/entrypoint/test_embeddings.py
Fixes #489 and fixes #446.
List of all "optimizations":
* When testing, don't load a large spacy model during `bbs_database add`. This should also eliminate OOM issues.
* Skip `spawn` multiprocessing method in tests of `compute_embeddings`.  The default is `forkserver` and that one we don't skip. I wanted to do more cleanup here, however, I gave up.
```
pytest -m ""  # run on my laptop
```
* `master`: 190s
* this PR: 152s
If you have some ideas how a minimal change in the source code could lead to significant speedups please feel free to share them.
> Speed up tests + avoid OOM issues

- src/bluesearch/database/article.py
- tests/unit/database/test_article.py
Fixes #496, #425 and #429.
The PR improves JATS Parsing:
- Do not `yield` empty paragraphs
- Replace `\xa0` and `\u2009` by spaces (check  abstract of `/raid/projects/bbs/pmc/comm_use/Trauma_Surg_Acute_Care_Open/PMC6045722.nxml` for concrete illustration)
- Replace double-slash by single-slash when possible. However, the structure is always changing so it is not possible to put single slash everywhere (for example the number of sections varies `./body/sec/sec/.../sec/p/`)
- For paragraphs into paragraphs, concatenate all children paragraphs into one big one. (still to be discussed)
(if needed)
(if needed)
(if needed)
> Improve JATS Parsing

- .github/workflows/ci.yaml
- docs/conf.py
- docs/source/api/bluesearch.database.article.rst
- docs/source/api/bluesearch.database.identifiers.rst
- docs/source/api/bluesearch.database.pdf.rst
- docs/source/api/bluesearch.database.rst
- docs/source/api/bluesearch.database.topic.rst
- docs/source/api/bluesearch.entrypoint.create_database.rst
- docs/source/api/bluesearch.entrypoint.database.add.rst
- docs/source/api/bluesearch.entrypoint.database.convert_pdf.rst
- docs/source/api/bluesearch.entrypoint.database.init.rst
- docs/source/api/bluesearch.entrypoint.database.parent.rst
- docs/source/api/bluesearch.entrypoint.database.parse.rst
- docs/source/api/bluesearch.entrypoint.database.rst
- docs/source/api/bluesearch.entrypoint.database.schemas.rst
- docs/source/api/bluesearch.entrypoint.embedding_server.rst
- docs/source/api/bluesearch.entrypoint.embeddings.rst
- docs/source/api/bluesearch.entrypoint.mining_cache.rst
- docs/source/api/bluesearch.entrypoint.mining_server.rst
- docs/source/api/bluesearch.entrypoint.rst
- docs/source/api/bluesearch.entrypoint.search_server.rst
- docs/source/api/bluesearch.rst
- docs/source/api/bluesearch.version.rst
- docs/source/whatsnew.rst
- src/bluesearch/entrypoint/database/convert_pdf.py
- tox.ini
Fixes #505 
This adds two new tox environments:
* `tox -e apidoc`
* `tox -e check-apidoc`
The first one generates the API docs the second one checks that the API docs are up-to-date.
I updated our CI to include the `check-apidoc` check.
A small change in `docs/conf.py` adds a link to the GitHub repo in the top banner of the docs.
(if needed)
(if needed)
(if needed)
> Test API docs in tox + CI

- requirements.txt
- setup.py
- src/bluesearch/database/download.py
- src/bluesearch/entrypoint/database/download.py
- tests/unit/database/test_download.py
- tests/unit/entrypoint/database/test_download.py
Fixes #512 
Implements the download logic for `biorxiv` and `medrxiv`.
Note that the entrypoints will ask you to enter the credentials!
To run the dry run
```bash
bbs_database download medrxiv -n 2021-10 output_folder
```
To run an actual download
```bash
bbs_database download biorxiv 2021-10 output_folder
```
(if needed)
(if needed)
(if needed)
> Implement `bbs_database download` for biorxiv and medrxiv

- docs/source/whatsnew.rst
- requirements.txt
- setup.py
- src/bluesearch/database/download.py
- src/bluesearch/entrypoint/database/download.py
- tests/unit/database/test_download.py
- tests/unit/entrypoint/database/test_download.py
Fixes #513 
This implements the `bbs_database download arxiv` command.
There are several open question to discuss:
- The downloads contain all published versions of a given article (`XXXv1.pdf`, `XXXv2.pdf`, ...)
- what do we want to do with them?
- when do we want to do it?
- Is it possible that a new article version is published later and added to the same folder? How do we check that? (if we want to do that at all)
- The current implementation shows an error if the starting date is earlier than April 2007, this is when the new arxiv IDs were introduced. It's easy to implement downloads from before April 2007, but:
- They are already pre-sorted into categories, e.g. `q-bio`, while the new ones aren't
- So do we only want to download `q-bio` in that case?
- If yes, do we mix the `q-bio` …
> Implement `bbs_database download` for arXiv

- docs/source/api/bluesearch.entrypoint.database.rst
- docs/source/api/bluesearch.entrypoint.database.topic_extract.rst
- src/bluesearch/database/topic.py
- src/bluesearch/entrypoint/database/parent.py
- src/bluesearch/entrypoint/database/parse.py
- src/bluesearch/entrypoint/database/topic_extract.py
- src/bluesearch/utils.py
- tests/data/jats_article.xml
- tests/unit/database/test_topic.py
- tests/unit/entrypoint/database/test_download.py
- tests/unit/entrypoint/database/test_parse.py
- tests/unit/entrypoint/database/test_topic_extract.py
- tests/unit/test_utils.py
Fixes #523.
- Creation of CLI `bbs_database topic-extract`
- Handle PMC source (for now only extract journal topic)
- Creation of a function `filter_files` used by `bbs_database parse` and `bbs_database topic-extract` CLI commands.
- Sometimes, we do not have any `NLM Title Abbreviation`, should we extracting another info (for example `Journal title`) when it is the case ?
- Do we want to handle article topics and when ? 
- Currently, we extract `name` of the MeSH, could it be possible to take the IDs instead ?
(if needed)
(if needed)
(if needed)
> Implement `topic-extract --source=pmc`

- tox.ini
This should be a temporary fix for https://github.com/docker/docker-py/issues/2928.
> Ignore deprecation warning emitted by the docker package

- src/bluesearch/database/article.py
- src/bluesearch/database/mining_cache.py
- src/bluesearch/database/topic.py
- src/bluesearch/embedding_models.py
- src/bluesearch/entrypoint/_helper.py
- src/bluesearch/entrypoint/database/parent.py
- src/bluesearch/entrypoint/database/parse.py
- src/bluesearch/entrypoint/database/topic_extract.py
- src/bluesearch/entrypoint/embeddings.py
- src/bluesearch/entrypoint/mining_server.py
- src/bluesearch/mining/eval.py
- src/bluesearch/server/mining_server.py
- src/bluesearch/utils.py
- src/bluesearch/widgets/mining_schema.py
- tests/unit/entrypoint/test__helper.py
- tests/unit/mining/test_attribute.py
- tests/unit/mining/test_pipeline.py
- tests/unit/widgets/test_mining_widget.py
- tests/unit/widgets/test_search_widget.py
This PR rewrites type annotations in `src/` and `tests/` to follow the new style introduced in [PEP 604](https://www.python.org/dev/peps/pep-0604/) and [PEP 585](https://www.python.org/dev/peps/pep-0585/). Basically, this means using:
- the shorthand `Type1 | Type2` to represent type union — so we get rid of `typing.Union` and `typing.Optional`
- the built-ins collection types instead of the generic duplicates from `typing` — so we get rid of the depracated `typing.Dict`, `typing.List`, `typing.Set`, ...
The output of 
-  `git grep -rIn "typing.*" src/  | sort -u`
- ` git grep -rIn "typing.*" tests/ | sort -u`
should show no trace of `Optional`, `Union`, `Set`, `Dict`, `List`, `Tuple`.
**NOTE** — There's only one exception to this cleanup I did, consisting in the class `Article` which …
> Use modern type annotations (PEP 604 + PEP 585)

- docs/source/whatsnew.rst
- src/bluesearch/database/identifiers.py
- tests/unit/database/test_identifiers.py
Partially fixes #507.
`generate_uid` now raises `ValueError` if all provided identifiers  are `None`.
See unit tests.
(if needed)
(if needed)
> `generate_uid` raises `ValueError` if all ids are `None`

- requirements.txt
- setup.py
- src/bluesearch/entrypoint/database/add.py
- src/bluesearch/entrypoint/database/init.py
- tests/integration/test_bbs_database.py
- tests/unit/database/test_cord_19.py
- tests/unit/test_embedding_models.py
This PR adds the `postgres` backend to the `init` and `add` entrypoints. It also adds it to the integration test `tests/integration/test_bbs_database.py`. 
Closes #499 
Fixes #527.
Why is the CI failing? There is this `PytestUnraisableExceptionWarning` ([docs](https://docs.pytest.org/en/6.2.x/reference.html#pytest.PytestUnraisableExceptionWarning)). There are several ways how to handle this:
- Figure out the core reason why it is raised and fix it
- Ignore it locally with `@pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")` - already done elsewhere in our sourc ecode
- Ignore it globally with `pytest -p no:unraisableexception`
- Abandon this test / change it so that no exception occurs (e.g. trying a different driver than `pg8000`?)
```
pytest -p …
```
> Postgres integration + experiments

- docs/source/api/bluesearch.database.rst
- docs/source/api/bluesearch.database.topic_info.rst
- docs/source/whatsnew.rst
- src/bluesearch/database/article.py
- src/bluesearch/database/topic.py
- src/bluesearch/database/topic_info.py
- src/bluesearch/entrypoint/database/download.py
- src/bluesearch/entrypoint/database/topic_extract.py
- tests/unit/database/test_topic_info.py
- tests/unit/entrypoint/database/test_download.py
- tests/unit/entrypoint/database/test_topic_extract.py
Fixes #539 .
This adds the `TopicInfo` data class that replaces the manual creation and copy-pasting of the structured dictionary that we have been using for this purpose so far.
* See new tests under `tests/unit/database/test_topic_info.py`
* Adjusted tests for old code pass
(if needed)
(if needed)
(if needed)
> Add the TopicInfo data structure

- .github/workflows/ci.yaml
- tox.ini
Fixes #560 .
Created a new env called "type" that runs static type checks via mypy. Also updated the CI workflow.
Also did small cleaning up of other envs, added env descriptions.
Run the new env using
```sh
tox -e type
```
The old "lint" env should not run mypy any more:
```sh
tox -e lint
```
To see the new env descriptions run
```sh
tox -va
```
(if needed)
(if needed)
(if needed)
> Tox: move mypy into a separate env

- src/bluesearch/entrypoint/database/parse.py
- tests/unit/entrypoint/database/test_parse.py
Fixes #559 
* The `bbs_database parse` was adjusted to also support ingesting of piped standard input
- Before:
```bash
bbs_database parse parser input_path output_dir
```
- After:
```bash
bbs_database parse parser input_path output_dir # still possible
echo "file_1.py file_2.py" | bbs_database parse parser output_dir # this one works too
```
* A shell script (see below an example) can take care of the creation of the string to be piped. Built from `awk` and `clip`.
First of all, create a bunch of empty files
```bash
touch 0.xml a.xml b.xml c.xml d.xml e.xml f.xml g.xml h.xml
```
Then create the following `output.csv`
```bash
path,element_in_file,accept,source …
```
> Connecting `topic-filter` and `parse`

- tests/integration/test_bbs_database.py
- tests/unit/database/test_cord_19.py
- tests/unit/test_embedding_models.py
- tox.ini
Fixes #580 
More info: https://docs.pytest.org/en/6.2.x/usage.html?highlight=unraisable#warning-about-unraisable-exceptions-and-unhandled-thread-exceptions
> Ignore pytest.PytestUnraisableExceptionWarning globally - fix

- docs/source/whatsnew.rst
- src/bluesearch/database/article.py
- src/bluesearch/database/topic.py
- src/bluesearch/entrypoint/database/parse.py
- tests/unit/database/test_article.py
Fixes #552.
Please provide here a summary of the changes introduced by this PR.
Please provide here instructions on how to test the changes introduced by this PR.
(if some changes cannot be tested by automated tests)
(if needed)
(if needed)
(if needed)
> Inconsistency: `parse` assumes unzipped `JATS XML` but topic-extract assumes zipped `.meca`

- src/bluesearch/entrypoint/database/parent.py
- tests/unit/entrypoint/database/test_parent.py
> Restrict logging level manipulation to `bluesearch` loggers

- src/bluesearch/database/download.py
- tests/unit/database/test_download.py
Fixes #585.
This PR fixes the CLI download error caused by arXiv papers with broken ID or version. See comments to #585 for details.
The solution implemented here is to simply skip such problematic papers. This is consistent with the fact that also arXiv cannot retrieve such articles (see e.g. https://arxiv.org/pdf/1808.02949v1.pdf).
Please provide here instructions on how to test the changes introduced by this PR.
(if some changes cannot be tested by automated tests)
(if needed)
> Skip download for arXiv articles with broken ID or version

- tox.ini
CI was failing because of a new Warning from `luigi` package (`luigi.parameter.UnconsumedParameterWarning`)
> Trigger CI

- .github/workflows/ci.yaml
- tox.ini
Fixes #636.
From what I read on internet, I understand that a public repository has 20 concurrent jobs (see [here](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits)) but only 5 `macos` jobs (so it might be still a good idea to remove some python versions for `macos`).
(if needed)
(if needed)
(if needed)
> Remove python 3.7 from CI
